-- =====================================================================
-- CustomerLedger — InstallmentSchedules_CRUD.sql
-- Rows are only ever generated through plan creation (see the INSERT
-- below, one row per installment) — there is no ad-hoc schedule Create
-- screen. AmountPaid/Status are updated only through payment processing.
-- =====================================================================

USE customerledger;

-- ---------------------------------------------------------------------
-- INSERT (one row per installment number, generated by the application's
-- schedule-generation loop — InstallmentPlanService.GenerateSchedule)
-- ---------------------------------------------------------------------
INSERT INTO InstallmentSchedules (InstallmentPlanId, InstallmentNumber, DueDate, AmountDue, AmountPaid, Status, CreatedAtUtc)
VALUES (?, ?, ?, ?, 0, 'Pending', UTC_TIMESTAMP(6));

-- ---------------------------------------------------------------------
-- SELECT by primary key
-- ---------------------------------------------------------------------
SELECT InstallmentScheduleId, InstallmentPlanId, InstallmentNumber, DueDate, AmountDue, AmountPaid, PaidDate, Status
FROM InstallmentSchedules
WHERE InstallmentScheduleId = ?;

-- ---------------------------------------------------------------------
-- SELECT list (full schedule for one plan, in order)
-- ---------------------------------------------------------------------
SELECT InstallmentNumber, DueDate, AmountDue, AmountPaid, Status
FROM InstallmentSchedules
WHERE InstallmentPlanId = ?
ORDER BY InstallmentNumber;

-- ---------------------------------------------------------------------
-- Overdue installments (computed filter — see vw_OverdueInstallments for
-- the full reporting view; this is the underlying predicate on its own).
-- ---------------------------------------------------------------------
SELECT InstallmentScheduleId, InstallmentPlanId, InstallmentNumber, DueDate, AmountDue
FROM InstallmentSchedules
WHERE Status = 'Pending' AND DueDate < UTC_TIMESTAMP();

-- ---------------------------------------------------------------------
-- Controlled update through payment processing: record a payment against
-- one installment (application-service use only).
-- ---------------------------------------------------------------------
UPDATE InstallmentSchedules
SET AmountPaid = AmountPaid + ?,
    PaidDate = IF(AmountPaid + ? >= AmountDue, UTC_TIMESTAMP(6), PaidDate),
    Status = IF(AmountPaid + ? >= AmountDue, 'Paid', Status),
    UpdatedAtUtc = UTC_TIMESTAMP(6)
WHERE InstallmentScheduleId = ?;

-- ---------------------------------------------------------------------
-- Cancel only through the parent plan's workflow (not exposed
-- individually — bulk-cancels every remaining Pending row on a plan).
-- ---------------------------------------------------------------------
UPDATE InstallmentSchedules
SET Status = 'Cancelled', UpdatedAtUtc = UTC_TIMESTAMP(6)
WHERE InstallmentPlanId = ? AND Status = 'Pending';
